# -*- coding: utf-8 -*-
"""ATM_Machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDj-G06muF7_NpcY57SgCr2gJO-8sWsO
"""

account_A = 2009
account_B = 2008
password_A = 1234
password_B= 5678
def logging():
    while True:
        account = int(input("\nEnter the account number you want to log in: "))

        if account == account_A or account == account_B:
            break
        else:
            print("This account does not exist. Try again.")

    while True:
        password=int(input("Enter the password: "))
        if account== account_A:
          if password != password_A:
            print("Password Incorrect...")

          else:
            print("\nWelcome to your bank account ",account)
            break

        elif account== account_B:
          if password != password_B:
            print("Password Incorrect...")

          else:
            print("\nWelcome to your bank account ",account)
            break

    balance_A=10000
    balance_B=0
    return account,balance_A,balance_B

def check_balance(balance_A,balance_B,account):
    print("\nBALANCE")
    if account == "A":
        print("Remaining balance: ", balance_A)
    else:
        print("Remaining balance: ", balance_B)

deposit_amount = 0
def deposit_money(balance_A,balance_B,account):
    print("\nDEPOSIT MONEY")
    deposit_amount=int(input("Enter the amount you want to deposit: "))

    if account == "A":
        balance_A= balance_A +deposit_amount
        print("You have successfully deposited ",deposit_amount)
        print("New Balance: ",balance_A)

    else:
      balance_B= balance_B +deposit_amount
      print("You have successfully deposited ",deposit_amount)
      print("New Balance: ",balance_B)
    return balance_A,balance_B,deposit_amount

withdraw_amount=0
def withdraw_money(balance_A,balance_B,account):
    print("\nWITHDRAW MONEY")
    withdraw_amount=int(input("Enter the amount you want to withdraw: "))

    if account == "A":
        if withdraw_amount > balance_A:
            print("Insufficient balance!")
        else:
            balance_A = balance_A - withdraw_amount
            print("You have successfully withdrawn", withdraw_amount)
            print("New Balance: ",balance_A)
    else:
        if withdraw_amount > balance_B:
              print("Insufficient balance!")
        else:
            balance_B = balance_B - withdraw_amount
            print("You have successfully withdrawn", withdraw_amount)
            print("New Balance: ",balance_B)
    return balance_A,balance_B,withdraw_amount

def exiting():
    print("\nThank you!!Exiting...")


def transfer_money(balance_A,balance_B,account):
  print("\nTRANSFER MONEY")
  transfer_amount=int(input("Enter the amount you want to transfer: "))
  transfer_account=input("Enter the account name A/B you want to transfer the money: ")

  if account=="A":
      if transfer_amount > balance_A:
          print("Insufficient balance!")
      elif transfer_account=="B":
        balance_A -= transfer_amount
        balance_B += transfer_amount
        print("Transferred", transfer_amount, "from A to B")
        print("Remaining Balance in Account A: ",balance_A)

  elif account=="B":
    if transfer_amount > balance_B:
          print("Insufficient balance!")
    elif transfer_account=="A":
        balance_B -= transfer_amount
        balance_A += transfer_amount
        print("Transferred", transfer_amount, "from A to B")
        print("Remaining Balance in Account B: ",balance_B)

  return balance_A,balance_B,transfer_amount


history = []
def transaction_history(account, deposit_amount, withdraw_amount, transfer_amount):
    print("\nTRANSACTION HISTORY")
    print("Account:", account)
    for item in history:
      print(item)

def historyAppend_deposit(deposit_amount):
  history.append({
    "type": "deposit",
    "amount": deposit_amount
})


def historyAppend_withdraw(withdraw_amount):
  history.append({
    "type": "withdraw",
    "amount": withdraw_amount
})


def historyAppend_transfer(transfer_amount):
  history.append({
    "type": "transfer",
    "amount": transfer_amount
})


account,balance_A,balance_B=logging()


while True:
    print("\n 1. Check balance\n 2. Deposit money\n 3. Withdraw money\n 4. Transfer money\n 5. Transaction History\n 6. Exit ")
    service=int(input("Enter the number of the services above to obtain the service: "))

    while service < 1 or service > 6:
        print("\nInvalid input! Please enter a number between 1 and 5.")
        service=int(input("Enter the number of the services above to obtain the service: "))

    if service==1:
        check_balance(balance_A,balance_B,account)

    elif service==2:
        balance_A,balance_B,deposit_amount=deposit_money(balance_A,balance_B,account)
        historyAppend_deposit(deposit_amount )

    elif service==3:
        balance_A,balance_B,withdraw_amount=withdraw_money(balance_A,balance_B,account)
        historyAppend_withdraw(withdraw_amount)

    elif service==4:
      balance_A,balance_B,transfer_amount=transfer_money(balance_A,balance_B,account,)
      historyAppend_transfer(transfer_amount)

    elif service==5:
      transaction_history(account, deposit_amount, withdraw_amount, transfer_amount)

    else:
        exiting()
        break

