# -*- coding: utf-8 -*-
"""Movie Ticket Booking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgQH-wpar1KVXZafzDAF1XHTPj26BSIw
"""

username_A= "Sahanya"
password_A= 123

username_B= "Kuldhuni"
password_B= 456

username_C= "Siyansa"
password_C= 789


def logging():
  while True:
    username=input("Username :  ")
    password=int(input("Password : "))

    if username==username_A and password==password_A:
      print("Login Successful!")
      break
    elif username==username_B and password==password_B:
      print("Login Successful!")
      break
    elif username==username_C and password==password_C:
      print("Login Successful!")
      break
    else:
      print("Invalid Username and Password. Please re-enter. ")
      username=input("Username :  ")
      password=int(input("Password : "))

Bill=[]
frozen_seats=50
def frozen():
  while True:
    print("\nFROZEN")
    print("Available Seats for Frozen: ",frozen_seats)
    type=input("For adult or child:\nEnter 'A' for adult,'C' for children,'AC' for both: ")
    if type=="A":
      seat_amount=int(input("Enter amount of tickets: "))
      total_Fprice= seat_amount*frozen_adults
      Bill.append(["Frozen",type,seat_amount,total_Fprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="C":
      seat_amount=int(input("Enter amount of tickets: "))
      total_Fprice= seat_amount*frozen_children
      Bill.append(["Frozen",type,seat_amount,total_Fprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="AC":
      seat_amountA=int(input("Enter amount of tickets for adult: "))
      total_FpriceA= seat_amountA*frozen_adults
      Bill.append(["Frozen",type,seat_amountA,total_FpriceA])

      seat_amountC=int(input("Enter amount of tickets for children: "))
      total_FpriceC= seat_amountC*frozen_children
      Bill.append(["Frozen",type,seat_amountC,total_FpriceC])
      print(seat_amountA+seat_amountC,type,"tickets added to bill...")
      break


lionking_seats=30
def lionking():
  while True:
    print("\nLIONKING")
    print("Available Seats for Lion King: ",lionking_seats)
    type=input("For adult or child:\nEnter 'A' for adult,'C' for children,'AC' for both: ")
    if type=="A":
      seat_amount=int(input("Enter amount of tickets for adult: "))
      total_Lprice= seat_amount*lionking_adults
      Bill.append(["Lion King",type,seat_amount,total_Lprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="C":
      seat_amount=int(input("Enter amount of tickets for children: "))
      total_Lprice= seat_amount*lionking_children
      Bill.append(["Lion King",type,seat_amount,total_Lprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="AC":
      seat_amountA=int(input("Enter amount of tickets for adult: "))
      total_LpriceA= seat_amountA*lionking_adults
      Bill.append(["Lion King",type,seat_amountA,total_LpriceA])

      seat_amountC=int(input("Enter amount of tickets for children: "))
      total_LpriceC= seat_amountC*lionking_children
      Bill.append(["Lion King",type,seat_amountC,total_LpriceC])
      print(seat_amountA+seat_amountC,type,"tickets added to bill...")
      break

moana_seats=70
def moana():
  while True:
    print("\nMOANA")
    print("Available Seats for Moana: ",moana_seats)
    type=input("For adult or child:\nEnter 'A' for adult,'C' for children,'AC' for both: ")
    if type=="A":
      seat_amount=int(input("Enter amount of tickets for adult: "))
      total_Mprice= seat_amount*moana_adults
      Bill.append(["Moana",type,seat_amount,total_Mprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="C":
      seat_amount=int(input("Enter amount of tickets for children: "))
      total_Mprice= seat_amount*moana_children
      Bill.append(["Moana",type,seat_amount,total_Mprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="AC":
      seat_amountA=int(input("Enter amount of tickets for adult: "))
      total_MpriceA= seat_amountA*moana_adults
      Bill.append(["Moana",type,seat_amountA,total_MpriceA])

      seat_amountC=int(input("Enter amount of tickets for children: "))
      total_MpriceC= seat_amountC*moana_children
      Bill.append(["Moana",type,seat_amountC,total_MpriceC])
      print(seat_amountA+seat_amountC,type,"tickets added to bill...")
      break

cinderella_seats=30
def cinderella():
  while True:
    print("\nCINDERELLA")
    print("Available Seats for Cinderella: ",cinderella_seats)
    type=input("For adult or child:\nEnter 'A' for adult,'C' for children,'AC' for both: ")
    if type=="A":
      seat_amount=int(input("Enter amount of tickets for adult: "))
      total_Cprice= seat_amount*cinderella_adults
      Bill.append(["Cinderella",type,seat_amount,total_Cprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="C":
      seat_amount=int(input("Enter amount of tickets for children: "))
      total_Cprice= seat_amount*cinderella_children
      Bill.append(["Cinderella",type,seat_amount,total_Cprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="AC":
      seat_amountA=int(input("Enter amount of tickets for adult: "))
      total_CpriceA= seat_amountA*cinderella_adults
      Bill.append(["Cinderella",type,seat_amountA,total_CpriceA])

      seat_amountC=int(input("Enter amount of tickets for children: "))
      total_CpriceC= seat_amountC*cinderella_children
      Bill.append(["Cinderella",type,seat_amountC,total_CpriceC])
      print(seat_amountA+seat_amountC,type,"tickets added to bill...")
      break

encanto_seats=30
def encanto():
  while True:
    print("\nENCANTO")
    print("Available Seats for Encanto: ",encanto_seats)
    type=input("For adult or child:\nEnter 'A' for adult,'C' for children,'AC' for both: ")
    if type=="A":
      seat_amount=int(input("Enter amount of tickets for adult: "))
      total_Eprice= seat_amount*encanto_adults
      Bill.append(["Encanto",type,seat_amount,total_Eprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="C":
      seat_amount=int(input("Enter amount of tickets for children: "))
      total_Eprice= seat_amount*encanto_children
      Bill.append(["Encanto",type,seat_amount,total_Eprice])
      print(seat_amount,type,"tickets added to bill...")
      break

    elif type=="AC":
      seat_amountA=int(input("Enter amount of tickets for adult: "))
      total_EpriceA= seat_amountA*encanto_adults
      Bill.append(["Encanto",type,seat_amountA,total_EpriceA])

      seat_amountC=int(input("Enter amount of tickets for children: "))
      total_EpriceC= seat_amountC*encanto_children
      Bill.append(["Encanto",type,seat_amountC,total_EpriceC])
      print(seat_amountA+seat_amountC,type,"tickets added to bill...")
      break


def checkout():
  print("\nCHECKOUT")
  for item in Bill:
        print(
            "Movie Name:", item[0],
            "| Adult/Child/Both:", item[1],
            "|Ticket amount:",item[2],
            "| Total Price: Rs.", item[3]
        )
  total = 0

  for item in Bill:
        total += item[3]

  print("Total Bill: Rs.", total)
  print("Checkout Successful!!")

frozen_adults= 1000
frozen_children= 500

lionking_adults= 2000
lionking_children= 1500

moana_adults= 1500
moana_children= 1000

cinderella_adults= 1000
cinderella_children= 500

encanto_adults= 2000
encanto_children= 1500


logging()
while True:
  print("\nWelcome to our Cinema")
  print("\nAvailable Movies")
  print("1.FROZEN   : adult Rs.",frozen_adults,"| children Rs.",frozen_children)
  print("2.LIONKING : adult Rs.",lionking_adults,"| children Rs.",lionking_children)
  print("3.MOANA    : adult Rs.",moana_adults,"| children Rs.",moana_children)
  print("4.CINDERELLA : adult Rs.",cinderella_adults,"| children Rs.",cinderella_children)
  print("5.ENCANTO : adult Rs.",encanto_adults,"| children Rs.",encanto_children)
  print("6.Checkout")
  service= int(input("Enter the number of the movie: "))

  if service==1:
    frozen()
  elif service==2:
    lionking()
  elif service==3:
    moana()
  elif service==4:
    cinderella()
  elif service==5:
    encanto()
  else:
    checkout()
    break

