# -*- coding: utf-8 -*-
"""Resturant System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzDePiMDx12pfInssulwkhNgAhZUPJJn
"""

username_A= "Sahanya"
password_A= 123

username_B= "Kuldhuni"
password_B= 456

username_C= "Siyansa"
password_C= 789


def logging():
  while True:
    username=input("Username :  ")
    password=int(input("Password : "))

    if username==username_A and password==password_A:
      print("Login Successful!")
      break
    elif username==username_B and password==password_B:
      print("Login Successful!")
      break
    elif username==username_C and password==password_C:
      print("Login Successful!")
      break
    else:
      print("Invalid Username and Password. Please re-enter. ")


burger_price= 600
pizza_price= 2000
fries_price= 500
juice_price=550

cart=[]
def food_menu():
  print("\n FOOD MENU")
  print("\n1.Burger:Rs.",burger_price)
  print("2.Pizza:Rs.",pizza_price)
  print("3.Fries:Rs.",fries_price)
  print("4.Juice:Rs.",juice_price)
  print("5.Main Menu")
  while True:
    food_service=int(input("\nEnter the number of the food to add to cart: "))
    if food_service == 5:
            print("Exiting the food menu...")
            break
    amount=int(input("Enter the amount: "))

    if food_service==1:
      exsit = False
      for item in cart:
          if item[0] == "Burger":
              item[1] += amount
              item[2] += burger_price * amount
              exsit = True
              break

      if exsit == False:
          total_Bprice=burger_price*amount
          cart.append(["Burger",amount,total_Bprice])
          print(amount,"Burger added to cart...")


    elif food_service==2:
      exsit = False
      for item in cart:
          if item[0] == "Pizza":
              item[1] += amount
              item[2] += pizza_price * amount
              exsit = True
              break

      if exsit == False:
          total_Pprice=pizza_price*amount
          cart.append(["Pizza",amount,total_Pprice])
          print(amount,"Pizza added to cart...")


    elif food_service==3:
      exsit = False
      for item in cart:
          if item[0] == "Fries":
              item[1] += amount
              item[2] += fries_price * amount
              exsit = True
              break

      if exsit == False:
          total_Fprice=fries_price*amount
          cart.append(["Fries",amount,total_Fprice])
          print(amount,"Fries added to cart...")


    elif food_service==4:
      exsit = False
      for item in cart:
          if item[0] == "Juice":
              item[1] += amount
              item[2] += juice_price* amount
              exsit = True
              break

      if exsit == False:
          total_Jprice=juice_price*amount
          cart.append(["Juice",amount,total_Jprice])
          print(amount,"Juice added to cart...")



def viewcart():
  print("\nCART")
  for item in cart:
        print(
            "Food:", item[0],
            "| Amount:", item[1],
            "| Total Price: Rs.", item[2]
        )


def checkout():
  print("\nCHECKOUT")
  for item in cart:
        print(
            "Food:", item[0],
            "| Amount:", item[1],
            "| Total Price: Rs.", item[2]
        )
  total = 0

  for item in cart:
        total += item[2]

  print("Total Bill: Rs.", total)
  print("Checkout Successful!!")




logging()

while True:
  print("\nWelcome to our Resturant !!")
  print("\n1.View food menu \n2.View Cart \n3.Checkout  ")
  service=int(input("Enter the number above to obtain a service: "))

  if service == 1:
    food_menu()

  elif service==2:
    viewcart()

  else:
    checkout()
